const data = {
  propertis: [
    {
      name: "nargila_1",
      category: "shirt",
      slug: "shirt nargila1",
      image: "/image/img_1.jpg",
      price: 120,
      countInStock: 10,
      brand: "suria",
      rating: 4,
      numReviews: 10,
      description: "high quelity shirt",
    },
    {
      name: "nargila_2",
      category: "shirt",
      slug: "shirt nargila2",
      image: "/image/img_2.jpg",
      price: 120,
      countInStock: 10,
      brand: "suria",
      rating: 4,
      numReviews: 10,
      description: "high quelity shirt",
    },
    {
      name: "nargila_3",
      category: "shirt",
      slug: "shirt nargila3",
      image: "/image/img_3.jpg",
      price: 120,
      countInStock: 10,
      brand: "suria",
      rating: 4,
      numReviews: 10,
      description: "high quelity shirt",
    },
    {
      name: "nargila_4",
      category: "shirt",
      slug: "shirt nargila4",
      image: "/image/img_4.jpg",
      price: 120,
      countInStock: 10,
      brand: "suria",
      rating: 4,
      numReviews: 10,
      description: "high quelity shirt",
    },
    {
      name: "nargila_5",
      category: "shirt",
      slug: "shirt nargila5",
      image: "/image/img_4.jpg",
      price: 120,
      countInStock: 10,
      brand: "suria",
      rating: 4,
      numReviews: 10,
      description: "high quelity shirt",
    },
    {
      name: "nargila_6",
      category: "shirt",
      slug: "shirt nargila5",
      image: "/image/img_4.jpg",
      price: 120,
      countInStock: 10,
      brand: "suria",
      rating: 4,
      numReviews: 10,
      description: "high quelity shirt",
    },
    {
      name: "nargila_7",
      category: "shirt",
      slug: "shirt nargila7",
      image: "/image/img_4.jpg",
      price: 120,
      countInStock: 10,
      brand: "suria",
      rating: 4,
      numReviews: 10,
      description: "high quelity shirt",
    },
  ],
};

export default data;
